# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from main import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel, QWidget
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from matplotlib.figure import Figure
from misc import *


def stop():
    print("Stop the bot")


def start():
    """
    This function starts the bot by calling scan_stocks() from the main.py file.
    """
    print("Start the bot")
    scan_stocks()


def watch_list_clicked(sym, name_of_stock_selected):
    """
    Return a function which is callable by clicked.connect for QPushButton.
    This function gets the name of the stock selected and does some actions with it
    such as changing the title of the stats area.
    """
    def event_watch_list():
        _translate = QtCore.QCoreApplication.translate
        name_of_stock_selected.setText(_translate("MainWindow", sym))
    return event_watch_list


class MplCanvas(FigureCanvasQTAgg):
    def __init__(self, parent=None, width=5, height=4, dpi=100):
        fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = fig.add_subplot(111)
        super(MplCanvas, self).__init__(fig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 50, 551, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.stats_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.stats_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.stats_grid_layout.setObjectName("stats_grid_layout")
        self.stats_frame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.stats_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stats_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stats_frame.setObjectName("stats_frame")
        self.stats_grid_layout.addWidget(self.stats_frame, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 260, 551, 291))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.plots_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.plots_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.plots_grid_layout.setObjectName("plots_grid_layout")
        self.plot_frame = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.plot_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plot_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot_frame.setObjectName("plot_frame")
        # add a plot to the plot frame
        sc = MplCanvas(self, width=5, height=4, dpi=100)
        sc.axes.plot([1,2,3,4,5,6,7,8,9], [10,1,20,30,40, 30, 20, 50, 60])
        # sc.axes.plot(show_plot())
        self.plots_grid_layout.addWidget(sc, 0, 0, 1, 1)

        self.plots_grid_layout.addWidget(self.plot_frame, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(580, 50, 211, 211))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.watch_list_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.watch_list_layout.setContentsMargins(0, 0, 0, 0)
        self.watch_list_layout.setObjectName("watch_list_layout")
        self.watch_list_scroll_area = QtWidgets.QScrollArea(self.gridLayoutWidget_3)
        self.watch_list_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.watch_list_scroll_area.setWidgetResizable(True)
        self.watch_list_scroll_area.setObjectName("watch_list_scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 193, 207))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.watch_list_scroll_area.setWidget(self.scrollAreaWidgetContents)
        # add the watchlist here
        self.name_of_stock_selected = QtWidgets.QLabel(self.centralwidget)

        self.watch_list_vbox = QtWidgets.QVBoxLayout()
        watch_list_symbols = get_watchlist_symbols()
        for sym in watch_list_symbols:
            clickable_symbol = QtWidgets.QPushButton(sym)
            clickable_symbol.clicked.connect(watch_list_clicked(sym, self.name_of_stock_selected))
            self.watch_list_vbox.addWidget(clickable_symbol)
        self.watch_list_widget = QWidget()
        self.watch_list_widget.setLayout(self.watch_list_vbox)
        self.watch_list_scroll_area.setWidget(self.watch_list_widget)

        self.watch_list_layout.addWidget(self.watch_list_scroll_area, 0, 0, 1, 1)

        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(580, 290, 211, 261))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.control_area_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.control_area_layout.setContentsMargins(0, 0, 0, 0)
        self.control_area_layout.setObjectName("control_area_layout")
        self.control_frame = QtWidgets.QFrame(self.gridLayoutWidget_4)
        self.control_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_frame.setObjectName("control_frame")
        self.control_start = QtWidgets.QPushButton(self.control_frame)
        self.control_start.setGeometry(QtCore.QRect(10, 120, 65, 25))
        self.control_start.setObjectName("control_start")
        self.control_start.clicked.connect(start)  # start the bot

        self.control_stop = QtWidgets.QPushButton(self.control_frame)
        self.control_stop.setGeometry(QtCore.QRect(130, 120, 65, 25))
        self.control_stop.setObjectName("control_stop")
        self.control_stop.clicked.connect(stop)  # stop the bot

        self.control_loss_label = QtWidgets.QLabel(self.control_frame)
        self.control_loss_label.setGeometry(QtCore.QRect(10, 160, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(10)
        self.control_loss_label.setFont(font)
        self.control_loss_label.setObjectName("control_loss_label")
        self.control_gain_label = QtWidgets.QLabel(self.control_frame)
        self.control_gain_label.setGeometry(QtCore.QRect(10, 190, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(10)
        self.control_gain_label.setFont(font)
        self.control_gain_label.setObjectName("control_gain_label")
        self.control_loss_money_label = QtWidgets.QLabel(self.control_frame)
        self.control_loss_money_label.setGeometry(QtCore.QRect(120, 160, 65, 25))
        font = QtGui.QFont()
        font.setFamily("Serif")
        self.control_loss_money_label.setFont(font)
        self.control_loss_money_label.setObjectName("control_loss_money_label")
        self.control_gain_money_label = QtWidgets.QLabel(self.control_frame)
        self.control_gain_money_label.setGeometry(QtCore.QRect(120, 190, 65, 25))
        font = QtGui.QFont()
        font.setFamily("Serif")
        self.control_gain_money_label.setFont(font)
        self.control_gain_money_label.setObjectName("control_gain_money_label")
        self.buying_power_label = QtWidgets.QLabel(self.control_frame)
        self.buying_power_label.setGeometry(QtCore.QRect(10, 10, 100, 25))
        self.buying_power_label.setObjectName("buying_power_label")
        self.daily_budget_label = QtWidgets.QLabel(self.control_frame)
        self.daily_budget_label.setGeometry(QtCore.QRect(10, 50, 100, 25))
        self.daily_budget_label.setObjectName("daily_budget_label")
        self.buying_power_money_label = QtWidgets.QLabel(self.control_frame)
        self.buying_power_money_label.setGeometry(QtCore.QRect(130, 10, 70, 25))
        font = QtGui.QFont()
        font.setFamily("Serif")
        self.buying_power_money_label.setFont(font)
        self.buying_power_money_label.setObjectName("buying_power_money_label")
        self.daily_budget_money_label = QtWidgets.QLabel(self.control_frame)
        self.daily_budget_money_label.setGeometry(QtCore.QRect(130, 50, 70, 25))
        font = QtGui.QFont()
        font.setFamily("Serif")
        self.daily_budget_money_label.setFont(font)
        self.daily_budget_money_label.setObjectName("daily_budget_money_label")
        self.control_area_layout.addWidget(self.control_frame, 0, 0, 1, 1)
        self.watch_list_label = QtWidgets.QLabel(self.centralwidget)
        self.watch_list_label.setGeometry(QtCore.QRect(580, 30, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(13)
        self.watch_list_label.setFont(font)
        self.watch_list_label.setObjectName("watch_list_label")
        #self.name_of_stock_selected = QtWidgets.QLabel(self.centralwidget)
        self.name_of_stock_selected.setGeometry(QtCore.QRect(20, 30, 211, 17))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(13)
        self.name_of_stock_selected.setFont(font)
        self.name_of_stock_selected.setObjectName("name_of_stock_selected")
        self.plot_label = QtWidgets.QLabel(self.centralwidget)
        self.plot_label.setGeometry(QtCore.QRect(20, 240, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(13)
        self.plot_label.setFont(font)
        self.plot_label.setObjectName("plot_label")
        self.control_area_label = QtWidgets.QLabel(self.centralwidget)
        self.control_area_label.setGeometry(QtCore.QRect(580, 270, 111, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_area_label.sizePolicy().hasHeightForWidth())
        self.control_area_label.setSizePolicy(sizePolicy)
        self.control_area_label.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(11)
        self.control_area_label.setFont(font)
        self.control_area_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.control_area_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.control_area_label.setObjectName("control_area_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu_robinhood_trader = QtWidgets.QMenu(self.menubar)
        self.menu_robinhood_trader.setObjectName("menu_robinhood_trader")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu_robinhood_trader.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.control_start.setText(_translate("MainWindow", "Start"))
        self.control_stop.setText(_translate("MainWindow", "Stop"))
        self.control_loss_label.setText(_translate("MainWindow", "Total Loss: "))
        self.control_gain_label.setText(_translate("MainWindow", "Total Gain:"))
        self.control_loss_money_label.setText(_translate("MainWindow", "0.00"))
        self.control_gain_money_label.setText(_translate("MainWindow", "0.00"))
        self.buying_power_label.setText(_translate("MainWindow", "Buying Power: "))
        self.daily_budget_label.setText(_translate("MainWindow", "Daily Budget:"))
        self.buying_power_money_label.setText(_translate("MainWindow", "0.00"))
        self.daily_budget_money_label.setText(_translate("MainWindow", "0.00"))
        self.watch_list_label.setText(_translate("MainWindow", "Watch List"))
        self.name_of_stock_selected.setText(_translate("MainWindow", "Select a Stock"))
        self.plot_label.setText(_translate("MainWindow", "Live Data"))
        self.control_area_label.setText(_translate("MainWindow", "Control Area"))
        self.menu_robinhood_trader.setTitle(_translate("MainWindow", "Robinhood Trader"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
